/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdbool.h>
#include "stm32f0xx.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#define LED_TIME_BLINK 300
#define LED_TIME_SHORT 100
#define LED_TIME_LONG 1000

volatile uint32_t Tick = 0;

void SysTick_Handler(void){
	Tick++;
}

void tlacitka(void){
	static uint16_t debounce_s1 = 0xFFFF;
	static uint16_t debounce_s2 = 0xFFFF;
	static uint32_t delay;
	static uint32_t off_time;
	bool s1 = GPIOC->IDR & (1<<1);
	bool s2 = GPIOC->IDR & (1<<0);

	if (Tick > delay + 5){
		debounce_s1 <<= 1;
		debounce_s2 <<= 1;
		if (s1) debounce_s1 |= 0x0001;
		if (debounce_s1 == 0x7FFF){
			off_time = Tick + LED_TIME_LONG;
			GPIOB->BSRR = (1<<0);
		}
		if (s2) debounce_s2 |= 0x0001;
		if (debounce_s2 == 0x7FFF){
			off_time = Tick + LED_TIME_SHORT;
			GPIOB->BSRR = (1<<0);
		}
	}
	if (Tick > off_time){
		GPIOB->BRR = (1<<0);
	}
}


void blikac(void)
{
	static uint32_t delay;

	if (Tick > delay + LED_TIME_BLINK) {
		GPIOA->ODR ^= (1<<4);
		delay = Tick;
	}
}

int main(void)
{
	SysTick_Config(8000);	// nastaveni 1ms

	RCC->AHBENR |= RCC_AHBENR_GPIOAEN | RCC_AHBENR_GPIOBEN | RCC_AHBENR_GPIOCEN; // enable
	GPIOA->MODER |= GPIO_MODER_MODER4_0; // LED1 = PA4, output
	GPIOB->MODER |= GPIO_MODER_MODER0_0; // LED2 = PB0, output
	GPIOC->PUPDR |= GPIO_PUPDR_PUPDR0_0; // S2 = PC0, pullup
	GPIOC->PUPDR |= GPIO_PUPDR_PUPDR1_0; // S1 = PC1, pullup
	RCC->APB2ENR |= RCC_APB2ENR_SYSCFGEN;

	while(1){
		blikac();
		tlacitka();
	}
}
